kind: Pod
apiVersion: v1
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app

spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"